/* runtime.md phase 5, slice 6: how the graphics runtime reaches the
 * text component written in Festina (runtime/festina/text.f).
 *
 * The component is linked only into programs that draw or measure
 * text, along with the bundled font's bytes (runtime/fonts/). The
 * object that carries those bytes -- generated by festina/cli.py, one
 * per compiler -- registers this table from a constructor. A program
 * without text never links it, never registers anything, and every
 * text call goes to Cairo exactly as before; so there is no stub to
 * link and nothing to keep in step between two definitions. */
#ifndef FESTINA_TEXT_HOOKS_H
#define FESTINA_TEXT_HOOKS_H

#include <stdint.h>

typedef struct {
    /* text.f's festinaTextMask / festinaTextWidth / festinaTextHeight,
     * compiled from Festina: `text` is the UTF-8 string, `px` the size,
     * `font` the font's bytes as a Festina arr[int]. */
    void *(*mask)(const char *text, int64_t px, void *font);
    int64_t (*width)(const char *text, int64_t px, void *font);
    int64_t (*height)(const char *text, int64_t px, void *font);
    const unsigned char *font;
    int64_t font_len;
} FestinaTextHooks;

void festina_text_register(const FestinaTextHooks *hooks);

#endif
